language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "FDOCKQVA+/UvJsEltx4p983PTPuA005qxWXmBmfgb7WVOvdB3EY30aJVZO7l5hBGKFPCaxZCP5t+pedwmdKzD5AiGEl1oVWi8np/G6h9aDH7HN+FaM7IgOoX5ccZN6o1hiaLHoQZGJe/mJDXAJ8FvHQeFnMk5bb3Crqyllw668aOZW3SP6WO3cYK81AD9r8sPk//IrnRB+aWtK57yAhQy+gfHsZCcjUcU1MH6KpCXoH0Mov9egQQ9U1+juBm4AeiNMAqh9H6TvpLeF3BCttvgyGhELH4xkrB778FCNMYlLt3tmZITkWjfuRN1XAtsBTEVO/CcMvXvvmHKuT1cp+Wou6t7INFjXuAcnkly5gQ/feAqSbvOaeho0mJ6qGltEIBeaTQ762M3cCQxAr69pDqwL9cpgZuGx9MjLNy8OeXrmh7fxjGwDHVrD9yhr2vx2OIjbVUB9dPv/AVQd2NSoiR6SSLZROHf2f9DzM56/7/MmbwD66xHnmNzOB5Cul9qM7ZemFZSniwDKVPZpLhh7F+HeoB4Ds+2QRwfxnAhprPXM84WXCe86OakNxNIxw+u6i62ybhsX4f2B34NmyodzJntclYYmArkWojbBgv5kKlz82AjvhWzEx1GoUswCIgzPbIldZcwnweoECxu+0wfKwKMNgh7RMZXWuCmuxdfvwiyt8="
  api_key: # e4a8
    secure: "O7DKqZ0FzY4OevDxSL4OJD797orXhjl/QhPXW/xPLcsEktEsDAL9x6Q4t9cAEaO5F5+pUrOWM9fKAMjs5MQ9zEuvJbMjHukw0arUtrZD5gU7MYZBFi4uvI9JctX0gojySAceuUKFsqjV3hynmcmIgWYhqpwbON2jTlx7MgVaA1VlihorfBKt5QzVcWP585TVecVmrr9VOrLH8na8tObmvOeRXnsYEUE1dTVqDmLUaunywsNP2NpxsB2Vsu283yfI1qa2zKdKqtRjvvRf2oamTA0ySHCcVNET0i2N9jhSnRnl4UIhxUy5PbU3c/CX3uny24IKk0STsSczpq7BsH+nrKatKuwTr8i2A+lrEvjbObHMWUEg5KQiqGQDCU6xaRxYpp7HpgjGfU0pZUq0obr1jNE+BpFsP2LXuUVmhV3v0dcIg2MYodQPNO56Irw+QzSYsf9P/LKfvg4urrZ0jSOBg0Rl4qiJnkgmrxYj1jfgYaXI5yXJdF62aH+Ax7eI+CI95oPBL7d+FcDxJ1D9zCgfOPuvpJm+0Cgr9Oqg+Fx9xesmVvPLD5rIM7b0lR88KYfEivWz3MosusIF5k87NABP/ftzEielG1mzkGOYpzHxdUsbm4xq1nLgwSUfaUR0VZZG1Km/NivvfER42o+bu4DFaGVhxuFPgtLrgidXuS7jF+I="
  on:
    tags: true
    node: lts/*
